### ISSUE TITLE
The Advanced Data Mapper UI may not have be able to process the _required attribute

### ISSUE THREAD

**Issue by jasonhoekstra** [schoolstacks/dataflow#4]
In the Advanced Data Mapper UI, ensure that it processes the _required attribute for cases when data may or may not exist in a CSV file

**Comment by ajtatum** [comment]
@jasonhoekstra - I can check this out over the weekend if you'd like. To review, the _required attribute was used mostly when we wanted to create child/related entities, so, for example, we wouldn't create a Score Result entity if the columns didn't exist in the spreadsheet, right? If so, could we implement something that would check the CSV for those columns without having the _required attribute? Another possible solution could be that the processor checks if the column exists for all properties; if it doesn't exist AND there's no default value then we wouldn't create the record.

**Comment by jasonhoekstra** [comment]
Updated and closing now with bypass on the ADM
